FROM node:24 AS builder
WORKDIR /app
RUN corepack enable

ARG NEXT_PUBLIC_SUBGRAPH_ENDPOINT
ARG NEXT_PUBLIC_SUBGRAPH_API_KEY
ARG NEXT_PUBLIC_SUBGRAPH_ID
ARG NEXT_PUBLIC_INFURA_KEY
ARG NEXT_PUBLIC_L1_RPC_URL
ARG NEXT_PUBLIC_L2_RPC_URL
ARG NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID

ENV NEXT_PUBLIC_SUBGRAPH_ENDPOINT=${NEXT_PUBLIC_SUBGRAPH_ENDPOINT} \
    NEXT_PUBLIC_SUBGRAPH_API_KEY=${NEXT_PUBLIC_SUBGRAPH_API_KEY} \
    NEXT_PUBLIC_SUBGRAPH_ID=${NEXT_PUBLIC_SUBGRAPH_ID} \
    NEXT_PUBLIC_INFURA_KEY=${NEXT_PUBLIC_INFURA_KEY} \
    NEXT_PUBLIC_L1_RPC_URL=${NEXT_PUBLIC_L1_RPC_URL} \
    NEXT_PUBLIC_L2_RPC_URL=${NEXT_PUBLIC_L2_RPC_URL} \
    NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}

COPY . .
RUN pnpm install --frozen-lockfile && pnpm run build

FROM node:24
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

EXPOSE 3000
CMD ["pnpm", "start"]
