name: Feature Request
description: Suggest an idea or enhancement for this project.
labels: ["needs-triage"]
type: feature

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a feature!**
        Please fill out the details below to help us understand your idea and how it could improve the project.

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when [...]"
      placeholder: Describe the problem or pain point this feature would solve.
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution or feature.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Mention any workarounds or other approaches you've thought about.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any other relevant info, mockups, or examples.

  - type: markdown
    attributes:
      value: |
        ---
        **Optional additional items**
