export const ALL_REGIONS = {
  global: "Global",
  fra: "Frankfurt",
  lax: "Los Angeles",
  lon: "London",
  mdw: "Chicago",
  nyc: "New York City",
  prg: "Prague",
  sin: "Singapore",
  sao: "São Paulo",
  atl: "Atlanta",
  hnd: "Tokyo",
  mad: "Madrid",
  mia: "Miami",
  mos2: "Moscow",
  sto: "Stockholm",
  syd: "Sydney",
  sea: "Seattle",
  tor: "Toronto",
  sjo: "San Jose",
  ash: "Nashua",
  hou: "Houston",
  atl2: "Atlanta 2",
} as const;
